In [1]:
import numpy as np
import random

In [2]:
np.random.random(1)

array([0.14807158])

In [3]:
np.random.random((3,3))

array([[0.33782937, 0.54604806, 0.06615882],
       [0.9260856 , 0.26889808, 0.78684074],
       [0.04174519, 0.48994779, 0.76754474]])

In [4]:
np.random.randint(1,3)

1

In [5]:
np.random.randint(1,4,(4,4))

array([[1, 2, 3, 1],
       [3, 1, 1, 1],
       [1, 3, 2, 3],
       [1, 1, 1, 1]])

In [6]:
np.random.randint(1,4,(4,3,3))

array([[[2, 2, 1],
        [2, 1, 1],
        [3, 1, 2]],

       [[2, 1, 3],
        [1, 3, 2],
        [2, 2, 1]],

       [[1, 3, 2],
        [2, 2, 1],
        [3, 3, 1]],

       [[1, 2, 2],
        [2, 3, 3],
        [2, 3, 2]]])

In [7]:
np.random.rand(3,3)

array([[0.83558128, 0.16891646, 0.51680307],
       [0.95363095, 0.66421262, 0.58382724],
       [0.71376872, 0.15171728, 0.58425431]])

In [8]:
np.random.rand(3)

array([0.05227195, 0.37334766, 0.25860145])

In [9]:
np.random.randn(3,3)

array([[-0.86849148, -1.4295339 ,  0.08380185],
       [ 0.9418019 , -1.83089625,  1.17887893],
       [-1.12993829, -0.0894447 ,  0.07816281]])

In [10]:
np.random.seed(10) # seed for repating same value without seed value change every time
np.random.randint(1,4,(2,3,3))

array([[[2, 2, 1],
        [1, 2, 1],
        [2, 2, 1]],

       [[2, 2, 3],
        [1, 2, 1],
        [3, 1, 3]]])

In [11]:
np.random.randint(1,4,(2,3,3))

array([[[1, 1, 1],
        [3, 1, 3],
        [3, 2, 1]],

       [[1, 3, 2],
        [3, 2, 2],
        [2, 2, 3]]])

In [12]:
np.random.seed(10)
np.random.randint(1,4,(2,3,3))

array([[[2, 2, 1],
        [1, 2, 1],
        [2, 2, 1]],

       [[2, 2, 3],
        [1, 2, 1],
        [3, 1, 3]]])

In [13]:
x= [1,2,3,4]

In [14]:
np.random.random(x)

array([[[[0.68535982, 0.95339335, 0.00394827, 0.51219226],
         [0.81262096, 0.61252607, 0.72175532, 0.29187607],
         [0.91777412, 0.71457578, 0.54254437, 0.14217005]],

        [[0.37334076, 0.67413362, 0.44183317, 0.43401399],
         [0.61776698, 0.51313824, 0.65039718, 0.60103895],
         [0.8052232 , 0.52164715, 0.90864888, 0.31923609]]]])

In [15]:
np.random.choice(x)

4

In [16]:
np.random.permutation(x)

array([2, 4, 1, 3])

In [17]:
np.random.permutation(x)

array([3, 2, 1, 4])

In [18]:
np.random.seed(10)
np.random.permutation(x)

array([3, 1, 4, 2])

In [19]:
np.random.seed(10) 
np.random.permutation(x)

array([3, 1, 4, 2])

In [20]:
for i in range(20) :
print(np.random.choice(x))

IndentationError: expected an indented block (<ipython-input-20-375c43ccd398>, line 2)